services:
  request-generator:
    build:
      context: .
      dockerfile: Dockerfile.request-generator
    depends_on:
      - web-server

  web-server:
    build:
      context: .
      dockerfile: Dockerfile.web-server

  tcpdump:
    build:
      context: .
      dockerfile: Dockerfile.tcpdump
    command: ["tcpdump", "-i", "any", "-A"]
    network_mode: "service:web-server"
