services:
  request-generator:
    build:
      context: .
      dockerfile: Dockerfile.request-generator
    depends_on:
      - web-server
  web-server:
    build:
      context: .
      dockerfile: Dockerfile.web-server
  tcpdump:
    build:
      context: .
      dockerfile: Dockerfile.tcpdump
    privileged: true
    cap_add:
      - ALL
    network_mode: "service:web-server"
